# Generated by Django 4.2.3 on 2023-07-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_finch_options_feeding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeding',
            options={'ordering': ('finch', '-date')},
        ),
        migrations.AlterField(
            model_name='feeding',
            name='date',
            field=models.DateField(verbose_name='Feeding Date'),
        ),
        migrations.AddConstraint(
            model_name='feeding',
            constraint=models.UniqueConstraint(models.F('date'), models.F('meal'), models.F('finch'), name='finch_feeding_daily_meal_unique', violation_error_message='This Finch was already fed this meal for this day.'),
        ),
    ]
